### ISSUE TITLE
Cannot Access Before Initialization

### ISSUE THREAD

**Issue by patientplatypus6** [facebookexperimental/Recoil#1668]
New to the library, but I have a selector that doesn't seem to work and I don't know why: 

Here are the atoms and associated selector - 

```

//boardsData / setBoardsData
const boards = atom({
  key: 'boards', 
  default: {submit: false, response: null}
})

//currentBoard / setCurrentBoard
const board = atom({
  key: 'board',
  default: "man"
})

//selectorCurrentBoard
const currentBoardSel = selector({
  key: 'currentBoardSel',
  get: ({get}) => {
    const boards = get(boards) <-- ERROR HERE
    const board  = get(board)

    if(boards.response!=null){
      var returnvar = {}
      boards.response.forEach(bd => {
        if (bd.mnemonic == board){
          returnvar = bd
        }
      });
      return returnvar;
    }else{
      return {
        board_name: 'main', 
        board_description: 'General Discussion', 
        nsfw: false, 
        mnemonic: 'man'
      } 
    }
  },
});
```

Here is the error - 

```
state.js:33 Uncaught ReferenceError: Cannot access 'boards' before initialization
    at get (state.js:33:1)
    at evaluateSelectorGetter (recoil.js:7367:1)
    at getValFromRunningNewExecutionAndUpdatedDeps (recoil.js:7455:1)
    at getSelectorValAndUpdatedDeps (recoil.js:7520:1)
    at recoil.js:7642:1
    at detectCircularDependencies (recoil.js:7626:1)
    at Object.selectorGet [as get] (recoil.js:7642:1)
    at getNodeLoadable (recoil.js:2411:1)
    at getRecoilValueAsLoadable (recoil.js:2635:1)
    at recoil.js:5235:1
```

Why is this an error? Shouldn't the selector just pull the default value? According to the tutorial (https://recoiljs.org/docs/basic-tutorial/selectors/) the selector references the atom directly afterwards in the file.

**Comment by mondaychen** [comment]
Can you provide the full code? e.g. your react component that uses this selector. Best if you can create an example in codesandbox.io

**Comment by patientplatypus6** [comment]
<img width="1512" alt="Screen Shot 2022-03-14 at 3 21 00 PM" src="https://user-images.githubusercontent.com/60800027/158245435-b31e8f6b-2400-47fc-8102-e2dfd0924711.png">

I just dragged my state.js file with all the recoil atoms and selectors into a code sandbox and then included recoil. No other dependencies, it just can't see `board`. Go to the `state.js` file lines 44 and 45 to see the sandbox picking up the problem.

**Comment by mondaychen** [comment]
Ah I see the issue now.
When you do
```
const boards = get(boards)
```

You are overriding `boards` that you've already defined. It has nothing to do with Recoil. You get the same error if you the following
```
const a = 1;
function func() {
  const a = a+1; // 'a' was used before it was defined.
}
```

You simply need a different name

**Comment by patientplatypus6** [comment]
Thanks! I hadn't realized that it wouldn't allow shadowing in that way, don't know why I didn't think of that. Thanks for the help!
