### ISSUE TITLE
"This component must be used inside a <RecoilRoot> component" with ReactPromiseModal

### ISSUE THREAD

**Issue by awe-sim** [facebookexperimental/Recoil#1771]
I use [React Promise Modal](https://github.com/prezly/react-promise-modal) to show dialog components. Internally, it creates a DIV in the document and mounts the given component inside it using the equivalent of:

```
const wrapper = document.createElement('div');
document.body.appendChild(wrapper);
render(<TestComponent />, wrapper);
```

If the TestComponent has a `useRecoilValue()` statement within, then the `render(<TestComponent />, wrapper)` call fails with the above error. The exact stack trace is as follows:

```
ncaught Error: This component must be used inside a <RecoilRoot> component.
    at err (recoil.js:16:1)
    at Object.notInAContext (recoil.js:3650:1)
    at updateRetainCount (recoil.js:3048:1)
    at useRetain_ACTUAL (recoil.js:4402:1)
    at useRetain (recoil.js:4360:1)
    at useRecoilValueLoadable (recoil.js:4813:1)
    at useRecoilValue (recoil.js:4839:1)
    at Y (ModalHelper.tsx:41:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at updateContainer (react-dom.development.js:25482:1)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26037:1)
    at render (react-dom.development.js:26103:1)
    at hideModal (ModalHelper.tsx:67:1)
    at myReactModal (ModalHelper.tsx:91:1)
```

I've traced the call to `useRetain_ACTUAL(toRetain)` method where the following calls:
```
const storeRef = useStoreRef$1();
const store = storeRef.current;
```
result in `store` being assigned equal to `defaultStore`:
```
function notInAContext() {
  throw Recoil_err('This component must be used inside a <RecoilRoot> component.');
}
const defaultStore = Object.freeze({
  getState: notInAContext,
  replaceState: notInAContext,
  getGraph: notInAContext,
  subscribeToTransactions: notInAContext,
  addTransactionMetadata: notInAContext
});
```

And consequently, any attempt to fetch a recoil state will result in this error thrown.

Is there a way around this problem?

**Comment by drarmstr** [comment]
If you want to reference a Recoil store that isn't directly an ancestor in the React component hierarchy you can use the [`useRecoilBridgeAcrossReactRoots_UNSTABLE()`](https://recoiljs.org/docs/api-reference/core/useRecoilBridgeAcrossReactRoots) hook.

**Comment by lyqline** [comment]
@awe-sim 请问找到解决方案了吗？
