### ISSUE TITLE
recoil-sync window is not defined in NextJS using SSR

### ISSUE THREAD

**Issue by mikeebee** [facebookexperimental/Recoil#1777]
Hello!

I'm seeing this error when trying to use `recoil-sync` with NextJS. I assume it's something to do with SSR.

```
index.js?46cb:352 Uncaught at getURL (file:///sites/node_modules/recoil-sync/cjs/index.js:2001:33)
    at <unknown> (file:///sites/node_modules/recoil-sync/cjs/index.js:2031:36)
    at useRecoilURLSync (file:///sites/node_modules/recoil-sync/cjs/index.js:2036:26)
    at useRecoilURLSyncJSON (file:///sites/node_modules/recoil-sync/cjs/index.js:2178:3)
    at RecoilURLSyncJSON (file:///sites/node_modules/recoil-sync/cjs/index.js:2185:3)
    at processChild (file:///sites/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (file:///sites/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (file:///sites/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (file:///sites/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (file:///sites/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
```

Recoil `7.2`
Recoil-sync `0.0.1-alpha.1`
NextJS `12.1.0`
React `17.0.2`

**Comment by mondaychen** [comment]
If you are doing it on server side, you'll need to specify your own `browserInterface` when calling `useRecoilURLSync` as it can be different in different SSR set-up. The default one ([code pointer](https://github.com/facebookexperimental/Recoil/blob/85a316f334cd50f383566b3ec8610782f5aa7cbd/packages/recoil-sync/RecoilSync_URL.js#L149)) is simply `window.document.location` for `getURL`. You can consider adding a null check to avoid the error.

**Comment by mondaychen** [comment]
On our side, maybe we should consider adding the null check by default? @drarmstr

**Comment by mikeebee** [comment]
@mondaychen ah ok, thanks! I gave this a quick whirl and I'm getting a new error on the page with the `<RecoilURLSyncJSON />` component.

```
TypeError: Invalid URL: 

This error happened while generating the page.

Uncaught at new NodeError (node:internal/errors:363:5)
    at onParseError (node:internal/url:537:9)
    at new URL (node:internal/url:613:5)
    at parseURL (sites/node_modules/recoil-sync/cjs/index.js:1917:15)
    at <unknown> (sites/node_modules/recoil-sync/cjs/index.js:2031:27)
    at useRecoilURLSync (sites/node_modules/recoil-sync/cjs/index.js:2036:26)
    at useRecoilURLSyncJSON (sites/node_modules/recoil-sync/cjs/index.js:2178:3)
    at RecoilURLSyncJSON (sites/node_modules/recoil-sync/cjs/index.js:2185:3)
    at processChild (sites/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (sites/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:
```

**Comment by zlever01** [comment]
Any updates or work around on this?

**Comment by drarmstr** [comment]
Since there is no browser with SSR rendering, would overriding all of the methods with `browserInterface` provide a workaround?

**Comment by mikeebee** [comment]
@mondaychen sorry for the delay, I had to abandon this in favour of my original `next/router` solution but I tried a few things in the `getURL` function:

1. The original `window.document.location` with a null check (Perhaps I was doing this wrong, could you give me an example?)
2. Incorporating `next/router`
3. Attempting to leverage [`URLSearchParams 'get'`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get)

**Comment by drarmstr** [comment]
I think a simple `null` check with `window` may actually fail with SSR and you may have to do a `typeof Window === 'undefined' || typeof window === 'undefined'` check...  Either way, try manually calling `new URL(...)` with whatever url you come up with to see if you get the parse error.

**Comment by mikeebee** [comment]
@drarmstr Apologies, I'm not following. I can make the check but how do I get the values from the URL without `window`?

```
getURL: () => {
  if (typeof Window === 'undefined' || typeof window === 'undefined') {
    // What do add here...
  } else {
   // ...or here but it never seems to make it to here
  }
},
```

**Comment by drarmstr** [comment]
If you're running on the browser and there is a `window` then you can return `window.document.location`.  If you're using SSR and running on the server then there is no browser to read the current URL from.  I'm not entirely sure how SSR apps access what there URL would be...  e.g. with React Router looks like it might come in as a `url` property of the first parameter in the callback to the express `get()` call?  ([here](https://reactrouter.com/docs/en/v6/guides/ssr) and [here](https://stackoverflow.com/questions/63119940/react-ssr-how-can-my-component-get-the-url-search-url-parameters-in-its-render))

**Comment by mikeebee** [comment]
I'm using [next/router](https://nextjs.org/docs/api-reference/next/router) btw.

I have access to the `route` (`ServerRouter`) object

```
ServerRouter {
  route: '/search/ports',
  pathname: '/search/ports',
  query: {},
  asPath: '/search/ports',
  isFallback: false,
  basePath: '',
  locale: undefined,
  locales: undefined,
  defaultLocale: undefined,
  isReady: false,
  domainLocales: undefined,
  isPreview: false,
  isLocaleDomain: false
}
```

I tried this:

```
import { useRouter } from 'next/router';

...

const router = useRouter();

...

getURL: () => {
  if (typeof Window === 'undefined' || typeof window === 'undefined') {
    return new URL(router.route, 'http://localhost:3000');
  }

  return '';
},
```

And got this error:

```
index.js?e46d:1911 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at parseURL (index.js?e46d:1911:1)
    at eval (index.js?e46d:2025:1)
    at useRecoilURLSync (index.js?e46d:2030:1)
    at useRecoilURLSyncJSON (index.js?e46d:2172:1)
    at RecoilURLSyncJSON (index.js?e46d:2179:1)
    at renderWithHooks (react-dom.development.js?ac89:14985:1)
    ... [truncated]
```

**Comment by drarmstr** [comment]
getURL() should just return a string, not a URL object.

**Comment by mikeebee** [comment]
Ah, my mistake!

Confirmed this is working

```
getURL: () => {
  return `http://localhost:3000${router.route}`;
},
```

Thank you for your patience in helping me with this.

**Comment by zlever01** [comment]
Thanks @mikeebee, this works for me as well, but I get an error when using `refine`. 
```
export const colorAtom = atom({
  key: "color", 
  default: "", 
  effects: [urlSyncEffect({ refine: string(), history: "push" })],
});
```
I get this error:
`ReferenceError: string is not defined`

Are you having issues with `refine`?

**Comment by drarmstr** [comment]
Yeah, the proper exporting/typing of `refine` is the current blocker for the `recoil-sync` release.  @mondaychen , is this currently being exported as a `refine` object to dereference `string` from or are they currently top-level exports?
