### ISSUE TITLE
[recoil-sync] useRecoilSync() raises Snapshot has already been released

### ISSUE THREAD

**Issue by ci7lus** [facebookexperimental/Recoil#1874]
Components using `recoil-sync.useRecoilSync` often encounter the following error:

```
Uncaught Error: Snapshot has already been released.
    at err (index.js:60:17)
    at Snapshot.retain (index.js:3657:15)
    at useRecoilSnapshot (index.js:5665:35)
    at useRecoilSync (index.js:347:20)
    at RecoilSharedSync (RecoilSharedSync.tsx:39:33)
    at renderWithHooks (react-dom.development.js:2691:157)
    at updateFunctionComponent (react-dom.development.js:3438:388)
    at beginWork (react-dom.development.js:3865:549)
    at HTMLUnknownElement.callCallback (react-dom.development.js:728:119)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:748:45)
```

`RecoilStoredSync.tsx`: https://github.com/ci7lus/MirakTest/blob/ee69ebe29382785dc172011a7a772aca34dfe7b4/src/components/global/RecoilSharedSync.tsx

## Environment

- react: 18.1.0
- react-dom: 18.1.0
- recoil: 0.7.3
- recoil-sync: 0.1.1-alpha.1

**Comment by drarmstr** [comment]
@ci7lus - Do you have a sandbox.io reproducer?
