### ISSUE TITLE
Async Data Query issue

### ISSUE THREAD

**Issue by Sleepy-GH** [facebookexperimental/Recoil#2077]
Hey all,

Let me start off by saying I'm pretty new to React and completely new to Recoil. So far I'm liking at as the learning curve seems a lot less steep to Redux (I don't even know where to begin when I look at Redux).

I'm trying to write my first spare-time frontend that talks to a backend, nothing fancy so far. But when I get it all hooked up and go to the page that should do the fetching I get this warning in the console:
```
Warning: Can't perform a React state update on a component that hasn't mounted yet. This indicates that you have a side-effect in your render function that asynchronously later calls tries to update the component. Move this work to useEffect instead.
    at Batcher (https://x59ew8.csb.app/node_modules/recoil/es/index.js:2732:45)
    at RecoilRoot_INTERNAL (https://x59ew8.csb.app/node_modules/recoil/es/index.js:2789:59)
    at RecoilRoot (https://x59ew8.csb.app/node_modules/recoil/es/index.js:2897:20)
```

Additionally when I want to then do something on the page I get another error about:
```
A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator.
```

I've recreated the issue the best I could in [this codesandbox](https://codesandbox.io/s/determined-kepler-x59ew8?file=/src/App.tsx). Am I just completely misunderstanding how to use this framework? Or am I overlooking something simple?

Thank you!

**Comment by tpAtalas** [comment]
Recoil is triggered before the suspense so You need to lift up the `suspense` like this. It will work:

```ts
export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <React.Suspense fallback={<span>Loading...</span>}>
        <PokemonDetail />
      </React.Suspense>
    </div>
  );
}
```
