### ISSUE TITLE
"window is not defined" - SSR support

### ISSUE THREAD

**Issue by gschultz49** [facebookexperimental/Recoil#34]
I received this error when attempting to retrieve the value from a selector. This occurs in a Next.js 9.4 project, which is inherently server side rendered. 

Looking through the source code it looks like there are a few references to the window object that aren't available in SSR. Are there any plans to support SSR? I tried to work around it by checking for the presence of the `window` object but because I'm trying to conditionally use state it breaks the [rules of hooks ](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) :(

```
ReferenceError: window is not defined
    at r (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:712)
    at C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:1276
    at e (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:1290)
    at C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:19654
    at i (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:19929)
    at Object.c [as get] (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:19966)
    at x (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:4554)
    at C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:6719
    at Object.replaceState (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:10416)
    at C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:6684
    at Object.trace (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:4312)
    at getRecoilValueAsLoadable (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:6652)
    at n (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:13390)
    at r (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:13682)
    at Object.getRecoilState (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:13775)
    at useRecoilState (C:\git\nextjs-workflows\node_modules\recoil\dist\recoil.js:1:14988)
```

Example consumer code:
```

export const projectNameState = selector({
  key: "projectName",
  get: ({ get }) => ...
});

export const ProjectNameProvider = () => {
  const [projectName, setProjectName] = useRecoilState(projectNameState);
  return (
    <ProjectNameComponent
      projectName={projectName}
      setProjectName={setProjectName}
    />
  );
};

```

**Comment by gschultz49** [comment]
Looking at the compiled source it looks to be related to the `window` in the `isNode` [function ](https://github.com/facebookexperimental/Recoil/blob/master/src/lib/Recoil_isNode.js#L14)
```
function isNode(object: mixed): boolean {
  const doc =
    object != null ? (object: $FlowFixMe).ownerDocument ?? object : document;
  const defaultView = doc.defaultView ?? window;
  return !!(
    object != null &&
    (typeof defaultView.Node === 'function'
      ? object instanceof defaultView.Node
      : typeof object === 'object' &&
        typeof object.nodeType === 'number' &&
        typeof object.nodeName === 'string')
  );
}
```

**Comment by davidmccabe** [comment]
We plan to support SSR but haven't really needed to try it yet. If you want to fix these window references that PR would be greatly appreciated.

**Comment by andreastoermer** [comment]
Hmmm ... i've tested this in a new next app and don't get the error.

**Comment by MuddyBootsCode** [comment]
I get the same error. React versions are:
 "react": "^16.12.0",
 "react-dom": "^16.12.0",
"next": "9.4",
"recoil": "0.0.7"

**Comment by pnfcre** [comment]
Hmm, I didn't get this error until the 0.0.8 update.

**Comment by pnfcre** [comment]
For now, I'll downgrade to 0.0.7.

**Comment by HelloEdit** [comment]
Can confirm the issue with recoil v0.0.8 & next.js v9.4.4

```
ReferenceError: window is not defined
    at Object.<anonymous> (/home/helloedit/Documents/projects/mensonge/interface/node_modules/recoil/dist/recoil.development.js:591:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/helloedit/Documents/projects/mensonge/interface/node_modules/recoil/dist/index.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at eval (webpack-internal:///recoil:1:18)
    at Object.recoil (/home/helloedit/Documents/projects/mensonge/interface/.next/server/static/development/pages/_app.js:149:1)
```

**Comment by bnol** [comment]
encountering the same error as @HelloEdit 
```recoil: 0.0.8
next: 9.4.4```
downgrading recoil to `v0.0.7` fixed the issue

**Comment by MathieuDoyon** [comment]
Same for me.

Other question how do you handling useRecoilValue because I have error that Nextjs ssr doesn't support React.Suspense?

**Comment by drarmstr** [comment]
@bnol , @MathieuDoyon  - Does #284 resolve this for you?

**Comment by ardaerzin** [comment]
@drarmstr 

I also had the same problem with recoil: 0.0.8, after updating today to 0.0.10 my project is running without any problems.

**Comment by baba43** [comment]
Having this problem again with `0.0.11`?

```
if (process.env.NODE_ENV !== "production") {
  window.$recoilComponentGetRecoilValueCount_FOR_TESTING = 0;
}
```
