### ISSUE TITLE
Nightly build broken

### ISSUE THREAD

**Issue by gurkerl83** [facebookexperimental/Recoil#903]
It seems the nighly builds are broken for a while, I get the following error.

```
error - TypeError: _options$cacheImpleme2.call is not a function
    at selectorFamily (/Users/markusgritsch/Development/Topics/Millipede/Project/millipede-docs/node_modules/recoil/cjs/recoil.js:7226:201)
    at Object.<anonymous> (/Users/markusgritsch/Development/Topics/Millipede/Project/millipede-docs/node_modules/recoil/cjs/recoil.js:7388:26)
```

The last working commitId of the nighlty branch is https://github.com/facebookexperimental/Recoil/tree/c8c2b9983229a56e008e1b48d25b9a9fe267ed31. 

Using the next in line commitId
https://github.com/facebookexperimental/Recoil/tree/1fcb9d7ab12632daf029177a761112d392d217fc up to the latest nightly produces the error.

It seems that the following commit had broken things https://github.com/facebookexperimental/Recoil/commit/c0ae9976933795b74669151caf86957049876e1f

Thx!

**Comment by mondaychen** [comment]
@csantos42 can you take a look?
