### ISSUE TITLE
ReferenceError: Window is not defined,  shouldNotBeFrozen

### ISSUE THREAD

**Issue by huanghaiyang** [facebookexperimental/Recoil#904]
![image](https://user-images.githubusercontent.com/5448818/109411326-32624880-79dc-11eb-84c9-ac8959744132.png)

**Comment by mondaychen** [comment]
In what environment?

**Comment by huanghaiyang** [comment]
weixin app

https://open.weixin.qq.com/

**Comment by pxue** [comment]
Runnign into this issue as well (in Node)

Typically when running tests, we can use https://www.npmjs.com/package/jsdom-global to ingest DOM globals, they handle the lowercased `window` (https://github.com/rstacruz/jsdom-global/blob/master/index.js#L37)

However, recoil is checking for the capitalized Window constructor function.
I'm not sure why check the constructor function instead of the instance?

**Comment by sanonz** [comment]
This seems to be a bug in the WeChat developer tools that can be fixed with the following snippet.

```js
if (!global.Window) {
  Object.defineProperty(global, 'Window', {
    value: window.constructor,
    writable: true,
    enumerable: true,
    configurable: true
  });
}
```

**Comment by pxue** [comment]
For future Googlers.

I ran into a similar issue running tests. jsdom-global injests global.window but not global.Window (Recoil use it to jump out of a recursive call).

adding `NODE_ENV=production` fixed this issue since it bypasses the shouldNotBeFrozen code execution path, and this is correct because you should be running tests in production anyway.

**Comment by flowertaekk-dev** [comment]
I'm struggling with the same error but different environment.

I am working on Next.js with typescript, jest, and enzyme.
whenever I try to test a component which is containing Recoil, the test failed with error like below.

```
    ReferenceError: Window is not defined

      at shouldNotBeFrozen (node_modules/recoil/cjs/recoil.js:5210:40)
      at deepFreezeValue (node_modules/recoil/cjs/recoil.js:5221:36)
      at setAtom (node_modules/recoil/cjs/recoil.js:6935:9)
      at setNodeValue (node_modules/recoil/cjs/recoil.js:788:10)
      at applyAction (node_modules/recoil/cjs/recoil.js:950:20)
      at node_modules/recoil/cjs/recoil.js:1007:7
      at Object.replaceState (node_modules/recoil/cjs/recoil.js:3240:34)
      at applyActionsToStore (node_modules/recoil/cjs/recoil.js:1003:9)
      at node_modules/recoil/cjs/recoil.js:1037:7
      at node_modules/recoil/cjs/recoil.js:1245:7
```

Does anyone know the solution for this?

**Comment by flowertaekk-dev** [comment]
> I'm struggling with the same error but different environment.
> 
> I am working on Next.js with typescript, jest(ts-jest), and enzyme.
> whenever I try to test a component which is containing Recoil, the test failed with error like below.
> 
> ```
>     ReferenceError: Window is not defined
> 
>       at shouldNotBeFrozen (node_modules/recoil/cjs/recoil.js:5210:40)
>       at deepFreezeValue (node_modules/recoil/cjs/recoil.js:5221:36)
>       at setAtom (node_modules/recoil/cjs/recoil.js:6935:9)
>       at setNodeValue (node_modules/recoil/cjs/recoil.js:788:10)
>       at applyAction (node_modules/recoil/cjs/recoil.js:950:20)
>       at node_modules/recoil/cjs/recoil.js:1007:7
>       at Object.replaceState (node_modules/recoil/cjs/recoil.js:3240:34)
>       at applyActionsToStore (node_modules/recoil/cjs/recoil.js:1003:9)
>       at node_modules/recoil/cjs/recoil.js:1037:7
>       at node_modules/recoil/cjs/recoil.js:1245:7
> ```
> 
> Does anyone know the solution for this?

I was able to handle this error with @sanonz solution.
Sorry for asking this question before tried all of solutions here and thank you!!
